### DISCUSSION TITLE
Code of Post-02 3rd edition

### DISCUSSION THREAD

**Discussion by koleesch** [phil-opp/blog_os#1332] [Questions]
Hello,

I can't get running the code of post-02 in the 3rd edition.

The message from cargo build is:
error[E0432]: unresolved import `bootloader`
 --> build.rs:1:5
  |
1 | use bootloader::DiskImageBuilder;
  |     ^^^^^^^^^^ use of undeclared crate or module `bootloader`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `blog_os` (build script) due to 1 previous error

My build.rs is the following:
```rust
use bootloader::DiskImageBuilder;
use std::{env, path::PathBuf};

fn main() {
    // set by cargo for the kernel artifact dependency
    let kernel_path = env::var("CARGO_BIN_FILE_KERNEL").unwrap();
    let disk_builder = DiskImageBuilder::new(PathBuf::from(kernel_path));
}
```

Here is my cargo.toml from the main directory (not kernel)
```toml
[package]
name = "blog_os"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["kernel"]

[dependencies]

[build-dependcies]
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }
```
My toolchain.toml:
```toml
[toolchain]
channel = "nightly"
profile = "default"
targets = ["x86_64-unknown-none"]
components = ["rust-src", "llvm-tools-preview"]
```
So what is wrong?
