### ISSUE TITLE
Add a Xargo.toml for xargo 0.3.0

### ISSUE THREAD

**Issue by phil-opp** [phil-opp/blog_os#271]
The newest xargo version 0.3.0 only builds the core crate by default. In order to build `alloc` and `collections` as well we now need a file named `Xargo.toml` with the following contents:

```toml
[target.x86_64-blog_os.dependencies]
collections = {}
```

This seems to work, too (but I'm not sure if it's idiomatic):

```toml
[dependencies]
collections = {}
```
